{{- if gt (int .Values.replicaCount) 1 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "flaglite.fullname" . }}
  labels:
    {{- include "flaglite.labels" . | nindent 4 }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "flaglite.selectorLabels" . | nindent 6 }}
{{- end }}
