{{- if not .Values.jwt.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flaglite.fullname" . }}-jwt
  labels:
    {{- include "flaglite.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.jwt.secret }}
  {{ .Values.jwt.secretKey }}: {{ .Values.jwt.secret | b64enc | quote }}
  {{- else }}
  {{ .Values.jwt.secretKey }}: {{ randAlphaNum 64 | b64enc | quote }}
  {{- end }}
{{- end }}
