apiVersion: v2
name: flaglite
description: FlagLite - Feature flags for everyone. Fast, simple, open-source.
type: application
version: 0.1.0
appVersion: "0.1.0"
keywords:
  - feature-flags
  - feature-toggles
  - rust
  - api
home: https://flaglite.dev
sources:
  - https://github.com/faiscadev/flaglite
maintainers:
  - name: Fa√≠sca Engineering
    email: engineering@faisca.dev

dependencies:
  - name: postgresql
    version: "16.x.x"
    repository: oci://registry-1.docker.io/bitnamicharts
    condition: postgresql.enabled
